import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ApolloClient, InMemoryCache, gql } from "@apollo/client";

export default function Home({ characters }) {
  console.log("charachters", characters);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>“Rick and Morty” adventure</h1>

        <p className={styles.description}></p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
        </div>
      </main>
    </div>
  );
}

// export async function getServerSideProps() {
//   const res = await fetch("https://rickandmortyapi.com/api/character");
//   const data = await res.json();
//   return {
//     props: { characters: data },
//   };
// }

export const getStaticProps = async () => {
  const client = new ApolloClient({
    uri: "https://rickandmortyapi.com/graphql",
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      # we give a default value of 1 to the variable
      query getCharacters($page: Int = 1) {
        characters(page: $page) {
          info {
            count
            pages
            next
            prev
          }
          results {
            name
          }
        }
      }
    `,
  });

  console.log("data", data);
  return {
    props: {
      characters: data,
    },
  };
};
